plugins {
    id 'com.github.ben-manes.versions' version '0.53.0'
}
apply plugin: 'groovy'

def moquiDir = file(projectDir.absolutePath + '/../../..')
def frameworkDir = file(moquiDir.absolutePath + '/framework')
def componentNode = parseComponent(project)
version = componentNode.@version

dependencyUpdates.resolutionStrategy = {
    componentSelection { rules ->
        rules.all { ComponentSelection selection ->
            boolean rejected = ['alpha', 'beta', 'rc', 'cr', 'm'].any { qualifier -> selection.candidate.version ==~ /(?i).*[.-]${qualifier}[.\d-]*/ }
            if (rejected) selection.reject('Release candidate')
        }
    }
}

repositories {
    flatDir name: 'frameworkLib', dirs: frameworkDir.absolutePath + '/lib'
//    flatDir name: 'localLib', dirs: projectDir.absolutePath + '/lib'
    mavenCentral()
    maven { url "https://packages.atlassian.com/maven-3rdparty/" }
}

dependencies {
    implementation project(':framework')
    implementation group: 'com.jhlabs', name: 'filters', version: '2.0.235-1'
    implementation group: 'com.octo.captcha', name: 'jcaptcha-api', version: '2.0-alpha-1'
    implementation group: 'com.octo.captcha', name: 'jcaptcha', version: '2.0-alpha-1'
    testImplementation project(':framework').configurations.testImplementation.allDependencies
}

// by default the Java plugin runs test on build, change to not do that (only run test if explicit task)
tasks.named('test') {
    enabled = false
}
task cleanLib(type: Delete) { delete fileTree(dir: projectDir.absolutePath + '/lib', include: '*') }
clean.dependsOn cleanLib

jar {
    destinationDirectory = file(projectDir.absolutePath + '/lib')
    // this is required to change from the default that includes the path to this module (ie 'runtime/base-componet/example')
    archiveBaseName = componentNode.@name
}

task copyDependencies {
    doLast {
        copy {
            from(configurations.runtimeClasspath - project(':framework').configurations.runtimeClasspath - project(':framework').tasks.jar.archiveFile.get().asFile)
            into file(projectDir.absolutePath + '/lib')
        }
    }
}
copyDependencies.dependsOn cleanLib
jar.dependsOn copyDependencies
